import { createElement } from '@lwc/engine-dom';
import Q3_AccountRealtedList from 'c/q3_AccountRealtedList';

describe('c-q-3-account-realted-list', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-q-3-account-realted-list', {
            is: Q3_AccountRealtedList
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});